name: Twenty Four Seven Application With MERN

'on':
  push:
    branches: develop

jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Build React Project
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache/Restore node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install React Dependencies and Build
        run: |
          mkdir public
          cd frontend
          npm install
          npm run build --if-present
        env:
          CI: false

      - name: List Output Files
        run: find public/ -print

      - name: Deploy Application
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
